clc;
clear all;
close all;
cd('C:\Users\LENOVO\Desktop\features\1');
A=xlsread('C:\Users\LENOVO\Desktop\features control.xlsx');
B=xlsread('C:\Users\LENOVO\Desktop\features amd.xlsx');
C=xlsread('C:\Users\LENOVO\Desktop\test c.xlsx');
D=xlsread('C:\Users\LENOVO\Desktop\test amd.xlsx');
t_1=A.T;
t_2=B.T;
training_data=[t_1{1:40,:};t_2{(1:40),:}];
t_3=C.T;
t_4=D.T;
testing_data=[t_3{(1:25),:};t_4{(1:32),:}];
g = [zeros(40,1);ones(40,1)];
[class,err,POSTERIOR,logp,coeff]=classify(testing_data,training_data,g,'quadratic');
% svmstruct = svmtrain(training_data,g);
% output = svmclassify(svmstruct,testing_data,'ShowPlot',true);
check = [zeros(25,1);ones(32,1)];
compare = class==check;
Accuracy_Percentage=rdivide(sum(compare,1),length(check))*100;